# Generated by Django 5.1.5 on 2025-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='des',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
