# Generated by Django 5.1.5 on 2025-01-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='des',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
