# Generated by Django 5.1.5 on 2025-01-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_full_name_alter_customuser_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='des',
            new_name='full_name',
        ),
    ]
