# Generated by Django 5.1.5 on 2025-02-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
